version: '3'

services:
  moviepilot-mcp:
    image: pollo3470/moviepilot-mcp:latest # 使用 Docker Hub 上的最新镜像
    container_name: moviepilot-mcp
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env # 从 .env 文件加载环境变量
