version: 1
disable_existing_loggers: false
formatters:
  default:
    (): uvicorn.logging.DefaultFormatter
    fmt: '%(levelprefix)s %(name)s: %(message)s'
    use_colors: true
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  '':
    handlers:
      - default
    level: DEBUG
