[project]
name = "moviepilot-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx[http2]>=0.28.1",
    "mcp[cli]>=1.6.0",
    "pydantic>=2.11.3",
]
